kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.16.4
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
- role: control-plane
  image: kindest/node:v1.16.4
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
- role: control-plane
  image: kindest/node:v1.16.4
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
- role: worker
  image: kindest/node:v1.16.4
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
- role: worker
  image: kindest/node:v1.16.4
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
- role: worker
  image: kindest/node:v1.16.4
  extraMounts:
  - hostPath: /dev
    containerPath: /dev
