#!/bin/bash

DESTINATION_NODE=$1

[ -n $2 ] && IDENTITY_FILE="-i $2"

SSH_USER=$3
SSH_PORT=$4

MAX_POD_CREATION_TIME=10

POD_NAME=sshjump-$(head /dev/urandom | tr -dc a-z0-9 | head -c 7 ; echo '')

# Install an SSH Server if not yet installed
r=$(kubectl get pod ${POD_NAME} -n default 2>/dev/null | tail -1 | awk '{print $1}') #
if [ "${r}" != "${POD_NAME}" ];then
echo "Creating SSH jump host (Pod)..."
kubectl run ${POD_NAME} -n default --image=corbinu/ssh-server --port=22 --restart=Never
# Wait until sshjump gets ready
c=1
while [[ ${c} -le ${MAX_POD_CREATION_TIME} ]];
do
    pod_status=$(kubectl get pod ${POD_NAME} -n default 2>/dev/null | tail -1 | awk '{print $3}')
    if [ "${pod_status}" = "Running" ]; then
    break
    fi
    (( c++ ))
    sleep 1
done
fi


# Setup portforward
RANDOM_PORT_FORWARDING=$(comm -23 <(seq 49152 65535 | sort) <(ss -Htan | awk '{print $4}' | cut -d':' -f2 | sort -u) | shuf | head -n 1)
kubectl port-forward -n default ${POD_NAME} ${RANDOM_PORT_FORWARDING}:22 2>/dev/null &
pid_port_forward=$!

ssh-add -L | kubectl exec -i ${POD_NAME} -n default -- /bin/bash -c "cat > /root/.ssh/authorized_keys"

ssh $DESTINATION_NODE $IDENTITY_FILE \
    -l ${SSH_USER:-centos} -p ${SSH_PORT:-22} \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o ProxyCommand="ssh -q -W %h:%p root@127.0.0.1 -p ${RANDOM_PORT_FORWARDING}"

kill -3 ${pid_port_forward} 2>/dev/null

kubectl delete pod ${POD_NAME} -n default --force