load_module /usr/lib/nginx/modules/ngx_http_stream_server_traffic_status_module.so;
load_module /usr/lib/nginx/modules/ngx_stream_server_traffic_status_module.so;

pid /tmp/nginx.pid;

worker_processes 1;
worker_rlimit_nofile 130048;
worker_shutdown_timeout 10s;

error_log /dev/stderr warn;

events {
    multi_accept on;
    worker_connections 1024;
    use epoll;
}

# The stream block handles TCP/UDP proxying
stream {
    server_traffic_status_zone;

    log_format proxy '$remote_addr [$time_local] listen=$server_port '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time "$upstream_addr"';
    access_log /dev/stdout proxy;

    upstream mysql {
        server 123.123.123.123:3306;
    }

    server {
        listen 13306;
        proxy_pass mysql;
        proxy_timeout 10m;
        proxy_connect_timeout 10m;
    }

}

http {
    stream_server_traffic_status_zone;

    server {
        listen 8080;

        location /status {
            stream_server_traffic_status_display;
            stream_server_traffic_status_display_format html;
        }
    }
}
