apiVersion: logging.banzaicloud.io/v1beta1
kind: FluentbitAgent
metadata:
  name: default
  namespace: logging-system
spec:
  positiondb:
    hostPath:
      path: ""
  bufferStorageVolume:
    hostPath:
      path: ""
  inputTail:
    Tag: kube.*
    Refresh_Interval: "60"
    Rotate_Wait: "5"
  filterKubernetes:
    Match: "kube.*"
    Annotations: "Off"
    Labels: "On"
    K8S-Logging.Parser: "On"
    K8S-Logging.Exclude: "On"
    Kube_Tag_Prefix: kube.var.log.containers
