apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: default
  namespace: logging-system
spec:
  fluentd: {}
  controlNamespace: logging-system
  allowClusterResourcesFromAllNamespaces: true
