apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: sandbox.project.ardikabs.internal
  name: spot-nodes
spec:
  associatePublicIp: false
  cloudLabels:
    ServiceName: application
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/sandbox.project.ardikabs.internal: "1"
  image: ami-00716eccd722c53ad
  machineType: c5.xlarge
  maxPrice: "0.09"
  maxSize: 5
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: spot-nodes
    on-demand: "false"
  role: Node
  rootVolumeSize: 8
  subnets:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c
