apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.0.2
    sans:
    - 192.168.0.2
    - 192.168.0.3
    - 192.168.0.4
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
