apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: sandbox.project.ardikabs.k8s.local
  name: regular-nodes
spec:
  associatePublicIp: false
  cloudLabels:
    ServiceName: application
    k8s.io/cluster-autoscaler/enabled: "1"
    k8s.io/cluster-autoscaler/sandbox.project.ardikabs.k8s.local: "1"
  image: ami-00716eccd722c53ad
  machineType: c5.xlarge
  maxSize: 3
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: regular-nodes
  role: Node
  rootVolumeSize: 8
  subnets:
  - ap-southeast-1a
  - ap-southeast-1b
  - ap-southeast-1c
