# Init Job used to initialize ECR Password login on every kink cluster initialization
# run only once
apiVersion: batch/v1
kind: Job
metadata:
  name: ecr-cred-helper-init
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: odaniait/aws-kubectl:latest
        imagePullPolicy: IfNotPresent
        name: ecr-cred-helper
        command:
        - /bin/sh
        - -c
        - |-
          SECRET_NAME=${AWS_ACCOUNT}-${AWS_DEFAULT_REGION}-ecr-registry
          TOKEN=$(aws ecr get-login-password)

          echo "ENV variables setup done."
          kubectl delete secret --ignore-not-found $SECRET_NAME
          kubectl create secret docker-registry $SECRET_NAME \
          --docker-server=https://${AWS_ACCOUNT}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com \
          --docker-username=AWS \
          --docker-password="${TOKEN}"

          echo "Secret created by name. $SECRET_NAME"
          kubectl patch serviceaccount default -p '{"imagePullSecrets":[{"name":"'$SECRET_NAME'"}]}'

          echo "All done."
        env:
          - name: AWS_ACCOUNT
            value: "123456789"
          - name: AWS_DEFAULT_REGION
            value: ap-southeast-1
          - name: AWS_SECRET_ACCESS_KEY
            value: aws-super-secret-access
          - name: AWS_ACCESS_KEY_ID
            value: AWSSUPERACCESSKEYID
        resources: {}
      dnsPolicy: Default
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
