apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin.org
  namespace: baz
spec:
  hosts:
    - httpbin.org
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: HTTPS
  resolution: DNS
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: httpbin-org
  namespace: baz
spec:
  host: httpbin.org
  subsets:
    - name: tls
      trafficPolicy:
        portLevelSettings:
          - port:
              number: 443
            tls:
              mode: SIMPLE
            connectionPolicy:
              http:
                idleTimeout: 600s # 10 minutes
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-org
  namespace: baz
spec:
  hosts:
    - httpbin.org
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: httpbin.org
            port:
              number: 443
            subset: tls
