apiVersion: apps/v1
kind: Deployment
metadata:
  name: k0s-kink-cluster
  labels:
    app: k0s-kink-cluster
    tier: k0s-master-plane
    type: kink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k0s-kink-cluster
      tier: k0s-master-plane
      mode: kink
  template:
    metadata:
      labels:
        app: k0s-kink-cluster
        tier: k0s-master-plane
        mode: kink
    spec:
      containers:
      - image: k0sproject/k0s:v0.9.1
        imagePullPolicy: Always
        name: k0s
        command:
          - "k0s"
        args:
          - server
          - -c
          - /etc/k0s/k0s.yaml
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /etc/k0s/k0s.yaml
            name: k0s-config
            subPath: k0s.yaml
      volumes:
        - name: k0s-config
          configMap:
            name: k0s-config
