apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- service.yaml
- deployment.yaml

configMapGenerator:
  - name: "k0s-config"
    files:
    - config/k0s.yaml
