apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: k0s-kink-cluster
spec:
  type: LoadBalancer
  ports:
  - port: 6443
    protocol: TCP
    targetPort: 6443
    name: 6443-tcp
  - port: 8132
    protocol: TCP
    targetPort: 8132
    name: 8132-tcp
  - port: 8133
    protocol: TCP
    targetPort: 8133
    name: 8133-tcp
  selector:
    app: k0s-kink-cluster
    tier: k0s-master-plane
    mode: kink

