FROM python:3.7-slim-stretch

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /app

RUN apt update -y \
    && apt install -y -f --no-install-recommends \
        sudo \
        wget \
        curl \
        git \
        build-essential \
        openssh-client \
        ca-certificates \
    && pip install ansible cryptography \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean