apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: proxy-echoserver-vs
  namespace: istio-testing
spec:
  hosts:
    - proxy-echoserver.istio-testing.svc.cluster.local
  gateways:
    - mesh
  http:
    - match:
        - uri:
            prefix: "/api"
      delegate:
        name: echoserver-mesh-dvs
        namespace: istio-testing
