apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: default
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: auto-ready-detector
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.5.0
