apiVersion: troubleshoot.sh/v1beta2
kind: Preflight
metadata:
  name: general
spec:
  analyzers:
    - clusterVersion:
        checkName: "Cluster Version"
        outcomes:
          - fail:
              when: "< 1.16.0"
              message: The application requires at least Kubernetes 1.16.0, and recommends 1.18.0.
              uri: https://kubernetes.io
          - warn:
              when: "< 1.18.0"
              message: Your cluster meets the minimum version of Kubernetes, but we recommend you update to 1.18.0 or later.
              uri: https://kubernetes.io
          - pass:
              message: Your cluster meets the recommended and required versions of Kubernetes.
    - nodeResources:
        checkName: "Node Memory Requirement"
        outcomes:
          - fail:
              when: "min(memoryAllocatable) < 7Gi"
              message: Minimum Node Memory capacity for deploying application is not met, should be at least 1Gi available
          - pass:
              when: "min(memoryAllocatable) >= 7Gi"
              message: The application able to be deployed
