apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/track: canary
    app.kubernetes.io/managed-by: manual
  name: podinfo-canary
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/track: canary
  ports:
    - name: http
      port: 9898
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 9999
      protocol: TCP
      targetPort: grpc
