apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: localhost
servers: 1
agents: 1
image: docker.io/rancher/k3s:v1.30.2-k3s2
kubeAPI:
  hostPort: "16443"
ports:
  - port: 6080:80
    nodeFilters:
      - loadbalancer
  - port: 6443:443
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: "60s"
    disableLoadbalancer: false
    disableRollback: true
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: --disable-network-policy
        nodeFilters:
          - server:*
      - arg: --flannel-backend=none
        nodeFilters:
          - server:*
      - arg: --service-cidr=10.251.0.0/16
        nodeFilters:
          - server:*
      - arg: --cluster-cidr=10.252.0.0/16
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
