apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: resource-leaker
  name: resource-leaker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: resource-leaker
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
