apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: google-com-vs
spec:
  hosts:
    - google.com
  http:
    - timeout: 3s
      route:
        - destination:
            host: httpbin.org
          weight: 100
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: httpbin-org-se
spec:
  hosts:
    - httpbin.org
  location: MESH_EXTERNAL
  ports:
    - name: http
      number: 80
      protocol: HTTP
  resolution: DNS
