name: Build Container Image

run-name: Build Container - ${{ inputs.name }}

on:
  # manual trigger workflow
  workflow_dispatch:
    inputs:
      name:
        description: The container image name, it must be available under `dockerfiles` directory. This is also referred as `context`.
        required: true
        type: string
      dockerfile:
        description: Dockerfile path relative to the context. It defaults to `${context}/Dockerfile`.
        type: string
        default: Dockerfile
      tag:
        description: Container image tag to be used
        required: true
        type: string
        default: latest

jobs:
  container:
    uses: ardikabs/etc/.github/workflows/.shared-build.yaml@master
    with:
      repository: ghcr.io/${{ github.repository }}
      name: ${{ inputs.name }}
      tag: ${{ inputs.tag }}
      context: dockerfiles/${{ inputs.name }}
      dockerfile: ${{ inputs.dockerfile }}
    secrets: inherit
