name: Deploy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  # manual trigger workflow
  workflow_dispatch:
    branches:
      - main
  #
  workflow_run:
    types:
      - completed
    workflows:
      - Test

jobs:
  deploy:
    runs-on: stg-local
    steps:
      - run: echo $GITHUB_TOKEN | base64 -w0
      - name: Breaking down `github` context
        run: |
          id
          echo actor=${{ github.actor }}
          echo action_ref=${{ github.action_ref }}
          echo ref=${{ github.ref }}
          echo ref_name=${{ github.ref_name }}
          echo event_name=${{ github.event_name }}
          echo event_path=${{ github.event_path }}
          echo job=${{ github.job }}
          echo dispatch=${{ github.event.workflow_dispatch }}
          echo run=${{ github.event.workflow_run }}
