name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "master"

jobs:
  unit-test:
    runs-on: stg-local
    environment: Development
    env:
      MY_ENV_VAR: "my env var"
    steps:
      - name: Sneak peek `github` context
        env:
          ALLSECRETS: ${{ toJSON(secrets) }}
          ALLENVS: ${{ toJSON(env)}}
          ALLVARS: ${{ toJSON(vars)}}
        run: |
          id
          echo actor=${{ github.actor }}
          echo action_ref=${{ github.action_ref }}
          echo ref=${{ github.ref }}
          echo ref_name=${{ github.ref_name }}
          echo event_name=${{ github.event_name }}
          echo event_path=${{ github.event_path }}
          echo job=${{ github.job }}
          echo PR=${{ github.event.pull_request.number }}
          echo PR_root=${{ github.event.number }}

          echo $ALLSECRETS
          echo $ALLENVS
          echo $ALLVARS
          echo
          echo
          printenv
